/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Avell 1511' at '10/9/17 8:38 AM' with Gradle 2.14.1
 *
 * @author Avell 1511, @date 10/9/17 8:38 AM
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
